
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    connection-timeout: 5000

spring:
  profiles:
    active: prod
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
      database: 0
      host: hejinyo.cn
      port: 6379
      password: redhat     # 密码（默认为空）
      timeout: 6000  # 连接超时时长（毫秒）
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

mybatis:
  type-aliases-package: cn.hejinyo.model
  mapper-locations: classpath*:cn/hejinyo/dao/*Dao.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    auto-mapping-behavior: full
    default-statement-timeout: 3600

pagehelper:
    helperDialect: mysql
    page-size-zero: true
    reasonable: true
    params: pageNum=start;pageSize=limit;pageSizeZero=zero;reasonable=heli;count=contsql
    row-bounds-with-count: true